### PR TITLE
Add CMake presets file

### PR DESCRIPTION
**Pull request by qjk-redlands**
Include a CMakePresets.json file. This defines the `runtimecore` configure preset, which defines the CMake variables used to configure zlib-ng for building.

This file is needed so that zlib-ng can be configured consistently in future upgrades.

### CODE REVIEW

**Comment by chri7325** [comment]
@qjk-redlands should we wait to introduce this once we move this library to CMake? I don't know what the plan is for 3rdparty yet but @cfrankmiller might have a different implementation of what that will look like away from these presets. In general, we try to keep 3rdparty to the bare minimum changes to easily manage history and seamless upgrades.

**Comment by qjk-redlands** [comment]
@chri7325 This cmake preset is intended to be used with the cmake configuration included by zlib-ng upstream. So separate from anything we may do in the future.

Since zlib-ng uses template files that only generate source when running a cmake configuration step, we need to track these presets somewhere so that we can upgrade zlib-ng in the future and regenerate source files from the templates.

I have an upgrade doc in progress with more details: https://devtopia.esri.com/runtime/runtimecore/blob/quinten/zlib-ng-upgrade-doc/docs/supporting_functional_areas/3rdparty/zlib_ng_upgrade.md

**Comment by chri7325** [comment]
@qjk-redlands I see. My previous work with 3rdparty was to document the CMake command in the commit message as well as in the doc. Would it be better to document the command using command line arguments instead? Something like `cmake -G "Unix Makefiles" -DSHARELIB=OFF ...`.  This CMakePresets.json file is at the root level here which might be a pattern that can cause friction for libraries that also use them, like we do in RTC. Here's an example of where I've documented the presets https://github.com/Esri/llvm-project/tree/runtimecore?tab=readme-ov-file#linux

**Comment by qjk-redlands** [comment]
@chri7325 Yep, makes sense to want to avoid adding this. In the case of zlib-ng and minizip-ng it works out since they don't have a cmake presets file, but that won't be the case for every 3rdparty library.

I will go ahead and add this information to the upgrade doc I'm writing. I think I prefer to add it there instead of to this project's readme (just bc that's another diff to look at when comparing `runtimecore` branch with upstream changes)

**Pull request closed without merging**
